version: "3.9"
services:
  chessaiwss:
    build:
      context: .
    image: chess-ai-wss-tcp:latest
    ports:
      - "${WS_PORT}:${WS_PORT}"
    environment:
      - WS_PORT
      - TCP_HOST
      - TCP_PORT
      - ENABLE_TCP_FORWARDING